sampleservice:
  build: .
sampledatastore:
  image: debian:wheezy
  volumes:
   - /var/data/TemplateStore:/data/db
sampledb:
  image: mongo
  volumes_from:
   - sampledatastore
queuedatastore:
  image: debian:wheezy
  volumes: 
   - /var/queue:/var/lib/rabbitmq/mnesia
queue:
  image: rabbitmq:management
  ports:
   - "8080:15672"
   - "5672:5672"
  volumes_from:
   - queuedatastore